### PR TITLE
Proposal

### PR DESCRIPTION
**Pull request by timunie**
don't mess with the command bindings everytime the selected item changes.

### CODE REVIEW

**Comment by Brayconn** [comment]
The Back button one is fine, but the Next Button _needs_ to be a binding.
The key feature is that each page has its own requirement(s) that must be met before the Next button will enable (see the example usage in [MainWindow.axaml](https://github.com/Brayconn/WizardExample/blob/master/WizardExample/Views/MainWindow.axaml)/[MainWindowViewModel.cs](https://github.com/Brayconn/WizardExample/blob/master/WizardExample/ViewModels/MainWindowViewModel.cs)).

**Comment by timunie** [comment]
But then you need to handle this in your VM. You can do this, but not how you did.

**Comment by timunie** [comment]
Also it is already a binding?

**Comment by timunie** [comment]
Are we talking about next button content?

**Comment by timunie** [comment]
See #2

**Comment by Brayconn** [comment]
> Are we talking about next button content?

To be clear, BackEnabled and NextContent can be determined automatically using the method in this PR, but NextEnabled needs to be determined by properties on the current page, meaning it needs to be a binding to the viewmodel/can't be determined solely in the control.

We can continue discussion in #2

**Pull request closed without merging**
